### ISSUE TITLE
Write-space optimization for pregelix messages and genomix-data structures.

### ISSUE THREAD

**Issue by jakebiesinger** [uci-cbcl/genomix#10]
@anbangx 

The messages we send are pretty big and sometimes they are larger than they need to be.  For example, KILL_SELF messages don't need to carry an entire node with them, nor a srcVertexId. Same goes for our Node class-- we often write len=0 for edges that don't exist.

One solution is to use either boolean values or a flag representing what data values are present in the stream.  We write the header to the stream.  When we read, we only call the readFields functions on the values that are actually present.

**Comment by anbangx** [comment]
@jakebiesinger 

I see what you mean. I did that before. I will do it after the test cases pass travis checking.

**Comment by jakebiesinger** [comment]
Fixed.
