### ISSUE TITLE
BUILD_HYRACKS still failing?

### ISSUE THREAD

**Issue by jakebiesinger** [uci-cbcl/genomix#11]
Hi @Nan-Zhang @JavierJia 

It seems the graphbuild using hyracks is still failing after our recent refactor? There is no output data when I run from the cmdline.

**Comment by JavierJia** [comment]
I haven't merge yet. Let me change the @anbangx  and @Nan-Zhang  as the CCer other than the reviewer and merge it back to the master.

**Comment by jakebiesinger** [comment]
Do you have a code review open for it?  I don't see it under reitveld...

**Comment by JavierJia** [comment]
Here it is: 
https://codereview.appspot.com/14573048/

**Comment by jakebiesinger** [comment]
Interesting... it doesn't show under "My reviews" in reitveld.  I guess once you say LGTM, the review is removed from your list.

Make sure to grab the latest fullstack off of github before you merge.  I think there were a few basic refactors to some files you removed-- that will make the merge annoying...

**Comment by JavierJia** [comment]
That might because I closed the issue ? 
I saw the genomix-hyracks tests passed on the Travis. I've merge it into fullstack. If you guys meet some problem while merging, please at me ~

**Comment by jakebiesinger** [comment]
Yeah, I think you're right.  You must have closed it.

**Comment by jakebiesinger** [comment]
BUILD_HYRACKS works now as of #12
