### ISSUE TITLE
hadoop /user/tmp is cleared automatically; the readid list disappears!

### ISSUE THREAD

**Issue by jakebiesinger** [uci-cbcl/genomix#117]
Hey @JavierJia we just tried to rerun some previous results on ipubmed2 and had a glaring realization... the filemanager dumps the readidset to disk under /user/tmp which (apparently) gets cleaned out automatically.  We tried to run some pipeline steps using data that was dumped on Thursday as input... there are many missing directories (though some are still intact).

With your #108, we gain the option to store the node in the local fs.  I think what we now need is a way to store the full set in the write() and read() calls.  Pregelix uses an adapter to dump from the vertex to an HDFS-based `Node`. I think in our output format,
we can explicitly set the readheadset to be dumped inside the node.  You should be able to add it somewhere aroung https://github.com/uci-cbcl/genomix/blob/genomix/fullstack_genomix/genomix/genomix-pregelix/src/main/java/edu/uci/ics/genomix/pregelix/base/GenericVertexToNodeOutputFormat.java#L34

I think this needs to be fixed ASAP...

cc @anbangx

**Comment by JavierJia** [comment]
I don't quite get the issue. About the /user/tmp automatically delete issue, we can change a directory to solve the problem . 

The other thing you mentioned is to add the automatic load the readHeadset from the HDFS when load the Node ?

**Comment by JavierJia** [comment]
fixed #118  #119
