### ISSUE TITLE
rerun with lower hadoop max tasks

### ISSUE THREAD

**Issue by Nan-Zhang** [uci-cbcl/genomix#19]
- [ ] update hadoop job conf's to use the driver-set values (should be equal to the length of IO_DIRS in the conf)
- [x] rerun hadoop graphbuild to use this many map tasks.

**Comment by jakebiesinger** [comment]
@JavierJia you mentioned today that this could be done by changing a setting in the JobConf. I've changed the title to include the work to make this happen.

**Comment by JavierJia** [comment]
I think the only way is to change the Hadoop mapred-site.xml to limit the maximum number of mapper. It can be set. But we should set it `before` start the Hadoop cluster.

**Comment by jakebiesinger** [comment]
Hmmm... so we can do it for local MR jobs that use the miniMR cluster, but
can't control the HDFS cluster that's already running.  Bummer.

## 

Jake Biesinger
Graduate Student
Xie Lab, UC Irvine

**Comment by anbangx** [comment]
Look into it more... @sigmod says that it should be 2x faster :smile:

**Comment by jakebiesinger** [comment]
Closing this issue with a reference to #10 and #16 for future sources of optimization.
