### ISSUE TITLE
Fix bubblemerge

### ISSUE THREAD

**Issue by Nan-Zhang** [uci-cbcl/genomix#21]
Bubble merge doesn't seem to affect the graph... Is it doing anything or are we too strict in our filtering?

**Comment by anbangx** [comment]
I plotted the subgraph starting from major vertices. All of them are not the simple nodes. It shows the simple bubble cases don't exist in our input file.  So not changing the graph structure after bubble merge step is correct.

**Comment by anbangx** [comment]
No simple bubble exists in our input file. Keep reporting to me if there is any error.
