### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by jakebiesinger** [uci-cbcl/genomix#3]
anbang, did you get this?

**Comment by jakebiesinger** [comment]
I'm referencing pull request #2 from this issue I raised earlier.

**Comment by anbangx** [comment]
Yep. I got it.

On Fri, Oct 18, 2013 at 11:25 AM, Jake Biesinger
notifications@github.comwrote:

> anbang, did you get this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/uci-cbcl/genomix/issues/3
> .

## 

Best Regards,

Anbang Xu
