### ISSUE TITLE
Automate genomix-hadoop/hyracks test compare code.

### ISSUE THREAD

**Issue by JavierJia** [uci-cbcl/genomix#6]
The hyracks automate test code is done. 
The hadoop automate test code is half done. The comparison between two is run under genomix-hadoop.

This task is to move the test code of comparison into genomix-driver. And make the it automatically.

**Comment by jakebiesinger** [comment]
This is a good idea but unfortunately only applies to graphbuilding, which is a pretty small subset of our codebase.

I think in the end, we're still going to need to have an `expected` output directory and we'll need to automatically check to make sure the `actual` matches.  This is complicated by the later steps' complexity: some jobs require graphbuilding and path merging before they can be applied. Perhaps we can make a bash script or something that would generate ALL the expected outputs for us, including chained jobs. Go ahead with this, but @anbangx you should have a look at this as well!

**Comment by JavierJia** [comment]
Yeah, it's a fairly smaller problem. I just come into this problem when clean up the test code on graph building. It could be a good start point for the other tests.

**Comment by anbangx** [comment]
Great! I will have a look at this. I think @JavierJia will help me generate the expected outputs of other tests :smile:

**Comment by JavierJia** [comment]
-[]
